version: 2
updates:
  - package-ecosystem: "npm"
    allow:
      - dependency-type: "all"
    directory: "/web/"
    schedule:
      interval: "weekly"
    groups:
      npm-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    allow:
      - dependency-type: "all"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      winit-wgpu-egui:
        patterns:
        - "winit"
        - "wgpu"
        - "naga"
        - "naga_oil"
        - "egui*"
        - "raw-window-handle"
      wasm-bindgen-dependencies:
        patterns:
        - "wasm-bindgen"
        - "js-sys"
        - "web-sys"
        - "wasm-bindgen-futures"
      gradle-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "tracing-tracy"
      - dependency-name: "tracy-client"