[package]
name = "ruffle_video_external"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ruffle_render = { path = "../../render" }
ruffle_video = { path = ".." }
swf = { path = "../../swf" }
slotmap = { workspace = true }
ruffle_video_software = { path = "../software" }
