[package]
name = "ruffle_frontend_utils"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
toml_edit = { version = "0.22.9", features = ["parse"] }
url = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
zip = "0.6.6"
urlencoding = "2.1.3"
ruffle_core = { path = "../core", default-features = false }
async-channel = { workspace = true }
slotmap = { workspace = true }

[dev-dependencies]
tempfile = "3"
