[target.'cfg(all())']
# NOTE that the web build overrides this setting in package.json via the RUSTFLAGS environment variable
rustflags = [
    # We need to specify this flag for all targets because Clippy checks all of our code against all targets
    # and our web code does not compile without this flag
    "--cfg=web_sys_unstable_apis",
]
