[package]
name = "ruffle_gc_arena"
version = "0.0.0"
description = "Temporary, internal gc-arena facade for Ruffle"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "764dd9bd00b618d4646265bf9ecc2b3280fbd80f" }
