# This is needed so we don't try to run too many visual tests at the same time,
# as they tend to crash on GitHub Actions runners - maybe due to not enough memory.
[[profile.ci.overrides]]
filter = "test(/^\\[render\\] /)"
threads-required = 4