name: AppImage Export

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev 
          
      #- name: Install appimagetool (based on Dockerfile)
      #  run: wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$(uname -m).AppImage -O /usr/local/bin/appimagetool  
          
      #- name: Mark appimagetool as executable
      #  run: chmod +x /usr/local/bin/appimagetool
        
      #- name: appimagetool "magic byte"
      #  run: sed -i 's|AI\x02|\x00\x00\x00|' /usr/local/bin/appimagetool
      
      - name: Install Cargo Packager
        run: cargo install cargo-packager --locked
        
      - name: Making empty src directory, to bypass issue with Cargo AppImage
        run: mkdir src
        
      - name: Show directory
        run: ls

      - name: Go into package directory
        run: cd desktop

      - name: Copy icon for Cargo Packager
        run: cp ./assets/favicon.ico ./favicon.ico

      - name: Cargo Packager
        run: cargo packager --release
        
      #- name: AppImage Export
      #  # APPIMAGE_EXTRACT_AND_RUN=1
      #  run: cargo appimage --package ruffle_desktop --verbose
      
      - name: Show directory
        run: ls
